[package]
name = "embedded-sdmmc-async"
version = "0.4.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
description = "A basic SD/MMC driver for Embedded Rust."
keywords = ["sdcard", "mmc", "embedded", "fat32"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-embedded-community/embedded-sdmmc-rs"
edition = "2021"
readme = "README.md"

[dependencies]
#embedded-hal = { version = "0.2.7", default-features = false }
embedded-hal-async = "1.0"
#embedded-hal-async = { version = "0.2.0-alpha.1", default-features = false }
byteorder = { version = "1", default-features = false }
log = { version = "0.4", default-features = false, optional = true }
defmt = { version = "0.3", optional = true }

[dev-dependencies]
hex-literal = "0.3"
env_logger = "0.9"

[features]
default = ["log"]
defmt-log = ["defmt"]
